<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param int $currentPage
     * @param int $limit
     * @return Paginator
     */
    public function getComments($currentPage = 1, $limit = 10)
    {
        // 
        $query = $this->createQueryBuilder('c')
                        ->where('c.status = 1', 'c.parentId is null')
                        ->orderBy('c.id', 'DESC')
                        ->getQuery();
        $paginator = $this->paginate($query, $currentPage, $limit);

        return $paginator;
    }
    
    /**
     * Get 
     * @param integer $currentPage The current page (passed from controller)
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function getLastCommentAddedBack($limit, $currentPage = 1)
    {
        // 
        $query = $this->createQueryBuilder('c')
                        ->orderBy('c.id', 'DESC')
                        ->getQuery();
        $paginator = $this->paginate($query, $currentPage, $limit);

        return $paginator;
    }
    
    /**
     *
     *   
     * @param integer            $page  
     * @param integer            $limit 
     *
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function paginate($dql, $page = 1, $limit = 10)
    {
        $paginator = new Paginator($dql);
        $paginator->setUseOutputWalkers(false);
        //$paginator->setUseOutputWalkers(false);
        
     
        $paginator->getQuery()
                ->setFirstResult($limit * ($page - 1)) 
                ->setMaxResults($limit); // Limit

        return $paginator;
    }
    
    public function getCommentsLastTen()
    {
        // Getting last 15 records for homepage on the back/admin. Returns array.
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT c.id, c.author, c.status, c.created, c.body FROM AppBundle:Comment c ORDER BY c.id DESC'
                        )->setMaxResults(15)
                        ->getResult();
    }
}
