<?php

namespace AppBundle\Repository;

/**
 * CounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CounterRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastVisit()
    {
        return $this->createQueryBuilder('e')
            ->orderBy('e.id', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
    }

    public function incrementVisit($id, $counter)
    {
        return $this->createQueryBuilder('e')
            ->update($this->getEntityName(), 'e')
            ->set('e.counter', $counter + 1)
            ->setParameter('id', $id)
            ->where('e.id = :id')
            ->getQuery()
            ->execute();
    }
}
