<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllQuizzes($limit, $currentPage = 1)
    {
        $query = $this->createQueryBuilder('u')
                ->orderBy('u.id', 'DESC')
                ->getQuery();
        $paginator = $this->paginate($query, $currentPage, $limit);

        return $paginator;
    }

    public function paginate($dql, $page = 1, $limit = 10)
    {
        $paginator = new Paginator($dql);
        $paginator->setUseOutputWalkers(false);


        $paginator->getQuery()
                ->setFirstResult($limit * ($page - 1))
                ->setMaxResults($limit);

        return $paginator;
    }

   public function updateTotal($last_num, $quizId)
   {
        $this->getEntityManager()
                ->createQuery(/** @lang mysql */
                        "UPDATE AppBundle:Quiz u SET u.total = $last_num WHERE u.id = $quizId")
                ->getResult();
   }

   public function getByStatusQuizId()
   {
        return $query = $this->getEntityManager()
                ->createQuery(
                        "SELECT u.quizName, u.id FROM AppBundle:Quiz u WHERE u.status = '1'  ORDER BY u.id DESC"
                )->getResult();
    }
}
