<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Post;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * Get posts by category for front/nav-back  dropdown
     * @param integer $currentPage The current page (passed from nav-back)
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function getAllQuizzes($currentPage = 1, $limit) {

        $query = $this->createQueryBuilder('u')
                ->orderBy('u.id', 'DESC')
                ->getQuery();
        $paginator = $this->paginate($query, $currentPage, $limit);

        return $paginator;
    }

    /**
     *
     *   
     * @param integer            $page  
     * @param integer            $limit 
     *
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function paginate($dql, $page = 1, $limit = 10) {
        $paginator = new Paginator($dql);
        $paginator->setUseOutputWalkers(false);
        //$paginator->setUseOutputWalkers(false);


        $paginator->getQuery()
                ->setFirstResult($limit * ($page - 1))
                ->setMaxResults($limit); // Limit

        return $paginator;
    }

   public function updateTotal($last_num, $quizId){
    $this->getEntityManager('u')
                        ->createQuery(
                                'UPDATE AppBundle:Quiz u SET u.total = ' .  $last_num . 'WHERE u.id = ' . $quizId)
                        ->getResult();
   }

   public function getByStatusQuizId() {
        // Getting last ten tests record from post. Returns array.
        return $query = $this->getEntityManager()
                        ->createQuery(
                                "SELECT u.quizName, u.id FROM AppBundle:Quiz u WHERE u.status = '1'  ORDER BY u.id DESC"
                        )->getResult();


    }
}
