contact_index:
    path:     /
    defaults: { _controller: "AppBundle:back/Contact:index" }
    methods:  GET

contact_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:back/Contact:show" }
    methods:  GET

contact_new:
    path:     /new
    defaults: { _controller: "AppBundle:back/Contact:new" }
    methods:  [GET, POST]

contact_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:back/Contact:edit" }
    methods:  [GET, POST]

contact_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:back/Contact:delete" }
    methods:  DELETE
