thoughts_index:
    path:     /
    defaults: { _controller: "AppBundle:back/Thoughts:index" }
    methods:  GET

thoughts_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:back/Thoughts:show" }
    methods:  GET

thoughts_new:
    path:     /new
    defaults: { _controller: "AppBundle:back/Thoughts:new" }
    methods:  [GET, POST]

thoughts_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:back/Thoughts:edit" }
    methods:  [GET, POST]

thoughts_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:back/Thoughts:delete" }
    methods:  DELETE
