video_index:
    path:     /
    defaults: { _controller: "AppBundle:back/Video:index", "currentPage":1}
    methods:  GET

video_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:back/Video:show" }
    methods:  GET

video_new:
    path:     /new
    defaults: { _controller: "AppBundle:back/Video:new" }
    methods:  [GET, POST]

video_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:back/Video:edit" }
    methods:  [GET, POST]

video_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:back/Video:delete" }
    methods:  DELETE

film_search:
    path:       /admin-pretraga-videa
    defaults:   { _controller: "AppBundle:back/Video:findVideos"}