<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ip extends \AppBundle\Entity\Ip implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'ip', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'proxy', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'client_ip', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'post_id', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'contact_id', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'comment_id', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'banned', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'created'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'ip', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'proxy', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'client_ip', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'post_id', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'contact_id', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'comment_id', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'banned', '' . "\0" . 'AppBundle\\Entity\\Ip' . "\0" . 'created'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ip $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIp($ip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIp', [$ip]);

        return parent::setIp($ip);
    }

    /**
     * {@inheritDoc}
     */
    public function getIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIp', []);

        return parent::getIp();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostId($post_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostId', [$post_id]);

        return parent::setPostId($post_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostId', []);

        return parent::getPostId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentId($comment_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentId', [$comment_id]);

        return parent::setCommentId($comment_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentId', []);

        return parent::getCommentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactId($contact_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactId', [$contact_id]);

        return parent::setContactId($contact_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactId', []);

        return parent::getContactId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProxy($proxy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProxy', [$proxy]);

        return parent::setProxy($proxy);
    }

    /**
     * {@inheritDoc}
     */
    public function getProxy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProxy', []);

        return parent::getProxy();
    }

    /**
     * {@inheritDoc}
     */
    public function setBanned($banned)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBanned', [$banned]);

        return parent::setBanned($banned);
    }

    /**
     * {@inheritDoc}
     */
    public function getBanned()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBanned', []);

        return parent::getBanned();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient_ip($client_ip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient_ip', [$client_ip]);

        return parent::setClient_ip($client_ip);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient_ip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient_ip', []);

        return parent::getClient_ip();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

}
